### ISSUE TITLE
Add libxlsxwriter topic to the GitHub project metadata

### ISSUE THREAD

**Issue by jmcnamara** [informationsea/xlsxwriter-rs#1]
Hi,

Could you add libxlsxwriter as a "topic" metadata to your project so that users can find wrappers in different languages.

Topic/Metadata are shown at the top of the project: https://github.com/jmcnamara/libxlsxwriter

Other examples: https://github.com/search?q=topic%3Alibxlsxwriter&type=Repositories

I'll probably add a section on language wrappings to the libxlsxwriter documentation.

Thanks,

John

**Comment by informationsea** [comment]
Thank you for your suggestion. I added tags to this project.
