### ISSUE TITLE
How to create a cell with a time value?

### ISSUE THREAD

**Issue by manfredlotz** [informationsea/xlsxwriter-rs#26]
I want to create a cell with a time value so that I have for example

* as value 05:00:00 PM 
* formatted as 17:00
* 
**Important:** There should be no date here.

In Libreoffice  in _Format Cells_ I would see
* Category: Time
* Format code: HH:MM

Creating the format sems easy
```
    let datetime_format = workbook.add_format()
         .set_num_format("hh:mm");
```

But I have no idea how to add a cell with a value, say 14:45h.

**Comment by jmcnamara** [comment]
> I want to create a cell with a time value so that I have for example

You need to create a xlsxwriter::DateTime object and set the year/month/day parts to 0. Like this:

```rust
use xlsxwriter::{DateTime, Workbook};

fn main() -> Result<(), xlsxwriter::XlsxError> {
    let workbook = Workbook::new("datetime.xlsx");
    let mut worksheet = workbook.add_worksheet(None)?;

    let time_format = workbook.add_format().set_num_format("hh:mm");

    worksheet.write_datetime(
        0,
        0,
        &DateTime::new(0, 0, 0, 17, 00, 0.0),
        Some(&time_format),
    )?;

    workbook.close()
}
```

Output:

![screenshot](https://user-images.githubusercontent.com/94267/207148711-1f90ced0-e059-4c31-b25f-4e47f68ba01b.png)

**Comment by manfredlotz** [comment]
Thanks a lot. Working fine. 

Only one small thing. 

Instead of 
```rust
let workbook = Workbook::new("datetime.xlsx");
```
it must be

```rust
let workbook = Workbook::new("datetime.xlsx")?;
```
