### ISSUE TITLE
Not able to export the huge data (more than 32767 characters)

### ISSUE THREAD

**Issue by SiriIO** [informationsea/xlsxwriter-rs#46]
```
use xlsxwriter::{ Workbook};

fn main() -> Result<(), xlsxwriter::XlsxError> {
    let workbook = Workbook::new("target/test.xlsx")?;

    let mut sheet1 = workbook.add_worksheet(None)?;

    
    sheet1.write_string(
        1,
        0,
       "more than 32767 characters string",
        None,
    )?;
     
    workbook.close()
}
```

Getting below error

`
Error: XlsxError { source: LibXlsxWriter(21) }
The terminal process "cargo 'run', '--package', 'hello-rust', '--bin', 'hello-rust'" terminated with exit code: 1.
`

<img width="1190" alt="Screenshot 2023-03-02 at 5 31 42 PM" src="https://user-images.githubusercontent.com/32861160/222423202-948ce6a2-b211-4624-a4ea-6143e7fc80f6.png">

**Comment by jmcnamara** [comment]
Maybe you are posting this issue in relation to the error message but Excel has a hard limit of 32767 characters in a cell. There is no workaround for that.

**Comment by informationsea** [comment]
As jmcnamara says, this is excel limitation that described in https://support.microsoft.com/en-us/office/excel-specifications-and-limits-1672b34d-7043-467e-8e27-269d656771c3
