### ISSUE TITLE
New release of libxlsxwriter-sys?

### ISSUE THREAD

**Issue by jqnatividad** [informationsea/xlsxwriter-rs#48]
Hi @informationsea , it's been a while since the release has been updated and it's still at v1.1.4

https://crates.io/crates/libxlsxwriter-sys

Can you make a new release?  Especially since v1.1.4 has a dependency on bindgen 0.59.2, which in turn depends on clap 2.34.0 which depends on the unmaintained ansi_term 0.12.1

https://rustsec.org/advisories/RUSTSEC-2021-0139

Thanks in advance!

**Comment by CHE1RON** [comment]
Since it's been a while, I'm bumping this. Since the last release dates back half a year, this would be much appreciated! Great project 🙏

**Comment by jqnatividad** [comment]
Thanks @informationsea for releasing xlsxwriter 0.6.0 and libxlsxwriter-sys 1.1.5.

It took care of the security advisory!
