### ISSUE TITLE
Paste a link with text alt in a cell

### ISSUE THREAD

**Issue by k-bx** [informationsea/xlsxwriter-rs#54]
I'd like to paste a text saying "Photo 1" which, upon click, leads to some photo link. It should look like this (in Ukrainian):

<img width="145" alt="зображення" src="https://github.com/informationsea/xlsxwriter-rs/assets/107968/b953d312-4bd6-4dde-b179-48b51b53da82">

Is it possible via current means of xlsxwriter-rs?

**Comment by jmcnamara** [comment]
Do you mean you want to link to some image within the file or to some image at an external URL?

**Comment by k-bx** [comment]
External url opened in browser, basically a web page.

**Comment by jmcnamara** [comment]
The wrapped libxlsxwriter library doesn't have a function/method for writing a url and specifying an alternative string like the Perl/Python version do. Instead, the suggested workaround is to writer the URL and then overwrite the cell with an alternative string with the same cell format.

Here is an `xlsxwriter.rs` example:

```rust
use xlsxwriter::{format::*, Workbook};

fn main() -> Result<(), xlsxwriter::XlsxError> {
    let workbook = Workbook::new("gh54.xlsx")?;

    let mut worksheet = workbook.add_worksheet(None)?;

    // Create a url format.
    let mut url_format = Format::new();
    url_format.set_font_color(FormatColor::Blue);
    url_format.set_underline(FormatUnderline::Single);

    let image_url = "https://docs.rs/-/rustdoc.static/rust-logo-151179464ae7ed46.svg";

    // Write a url.
    worksheet.write_url(0, 0, image_url, Some(&url_format))?;

    // Overwrite the displayed URL string with another string. Note, we need to
    // specify the format for the string to match the hyperlink.
    worksheet.write_string(0, 0, "Photo 1", Some(&url_format))?;

    workbook.close()
}
```

Output:

![screenshot](https://github.com/informationsea/xlsxwriter-rs/assets/94267/669c0d59-905d-4017-af52-a1b9ec54a3c1)

Sample file: [gh54.xlsx](https://github.com/informationsea/xlsxwriter-rs/files/13188486/gh54.xlsx)

**Comment by k-bx** [comment]
That's a clever hack, thank you! Created an upstream issue at https://github.com/jmcnamara/libxlsxwriter/issues/416 too

**Comment by jmcnamara** [comment]
> That's a clever hack, thank you! Created an upstream issue at [jmcnamara/libxlsxwriter#416](https://github.com/jmcnamara/libxlsxwriter/issues/416) too

That isn't really a hack. It is the documented way of doing it in libxlsxwriter. 

If it works for your use case you should close this issue.

**Comment by k-bx** [comment]
Oh, I see. I didn't check if it's possible in JS lib, but I was under an impression that the way they do it gives you an ability to insert multiple links via comma, like "Photo 1, Photo2, Photo3" all in single cell, each going to its own URL. I don't need it for now, can open a new issue later if needed.
